version: '3'
services: 
    frontend:
        build: 
            context: .
            dockerfile: dockerfile.dev
        volumes:
            - ./:/frontend
        ports:
            - "3000:3000"        
        volumes: 
            - ./:/frontend
            - /frontend/node_modules